#pragma once
#define Debug true
// NIP Engine Config
#define NE_VERSION "v0.7"
#define NE_TARGET_TICKRATE 60
#define NE_TICKRATE_TIME (1000 / NE_TARGET_TICKRATE)
#define NE_DELTATIME (1.0 / NE_TARGET_TICKRATE)
// FB Config
#define FB_CONTAINER_OUTPUT 100
#define FB_CONTAINER_SIZE 0.03
#define FB_IMAGE_SCALE 5
#define FB_IMAGE_SCALE_V2 5

#define FB_MOLECULE_COUNT 1
#define FB_MOLECULE_COL_BOUNDARY 1.000
#define FB_MOLECULE_SPAWNRANDOM true